#!/usr/bin/with-contenv bash
set -e

# Allow hostnames with more labels to be resolved. so that we can resolve node1.mycluster.local.
# (https://github.com/lathiat/nss-mdns#etcmdnsallow)
echo '*' > /etc/mdns.allow

# Configure NSSwitch to use the mdns4 plugin so mdns.allow is respected
sed -i "s/hosts:.*/hosts:          files dns mdns4/g" /etc/nsswitch.conf

# Configure Avahi-Daemon
sed -i '/^rlimit-nproc/s/^\(.*\)/#\1/g' /etc/avahi/avahi-daemon.conf
chmod 777 /etc/avahi/avahi-daemon.conf
mkdir -p /var/run/avahi-daemon
chown avahi:avahi /var/run/avahi-daemon
chmod 777 /var/run/avahi-daemon

# Configure dbus
mkdir -p /var/run/dbus/ 

# Setup logging
if [ -d /opt/iobroker/log ]; then
    chown -R iobroker /opt/iobroker/log
fi
