#!/usr/bin/with-contenv bash

#
#   This service passes the current ioBroker logfile to stdout
#

set -e

# Function to wait for a file to appear
wait_file() {
    local file="$1"; shift
    local wait_seconds="${1:-10}"; shift # default timeout 10 sec.

    until test $((wait_seconds--)) -eq 0 -o -e "$file" ; do sleep 1; done

    ((++wait_seconds))
}

wait_file "/opt/iobroker/log/iobroker.current.log" 600 && {
    # ioBroker logfile exists.
    exec tail -f -n 0 /opt/iobroker/log/iobroker.current.log
}
