#!/usr/bin/with-contenv bash
set -e

echo "Cleaning up ioBroker service ..."

# Check for stale ioBroker PID-files
if [ -f /opt/iobroker/node_modules/iobroker.js-controller/iobroker.pid ]; then
  echo "Removing stale PID-file iobroker.pid ..."
  rm -f /opt/iobroker/node_modules/iobroker.js-controller/iobroker.pid
fi

if [ -f /opt/iobroker/node_modules/iobroker.js-controller/pids.txt ]; then
  echo "Removing stale PID-file pids.txt ..."
  rm -f /opt/iobroker/node_modules/iobroker.js-controller/pids.txt
fi

echo "ioBroker service shutdown completed."
